/**********************************************************************************************************************
 * \file Button.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/




/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/

#include "Button.h"                 /* Include button public API */
#include "IfxPort.h"                /* Include GPIO APIs */
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/

/* Define button port */
#define BUTTON_PORT                 &MODULE_P14

/* Define button pin: P14.4 */
#define BUTTON_PIN                  4
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/

    /* Debug: full Port14 input register value */
    volatile uint32 g_debugP14_IN = 0;

    /* Debug: mask of LOW pins in Port14 */
    volatile uint32 g_debugP14LowMask = 0;

    /* Debug: 1 when button is pressed */
    volatile uint32 g_debugButtonPressed = 0;
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/

    /* Initialize button pin */
    void Button_Init(void)
    {
        /* Configure P14.4 as input pull-up */
        IfxPort_setPinModeInput(BUTTON_PORT, BUTTON_PIN, IfxPort_Mode_inputPullUp);
    }

    /* Return TRUE when button is pressed */
    boolean Button_IsPressed(void)
    {
        /* Read full Port14 input register */
        g_debugP14_IN = MODULE_P14.IN.U;

        /* Invert register to make LOW pins appear as 1 */
        g_debugP14LowMask = (~g_debugP14_IN) & 0xFFFFu;

        /* Check if P14.4 is LOW */
        if ((g_debugP14LowMask & (1u << BUTTON_PIN)) != 0u)
        {
            /* Store pressed state for debug */
            g_debugButtonPressed = 1;

            /* Return TRUE because button is pressed */
            return TRUE;
        }
        else
        {
            /* Store released state for debug */
            g_debugButtonPressed = 0;

            /* Return FALSE because button is released */
            return FALSE;
        }
    }
/*********************************************************************************************************************/
