/**********************************************************************************************************************
 * \file Buzzer.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/




/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
#include "Buzzer.h"                 /* Include buzzer public API */
#include "IfxPort.h"                /* Include GPIO APIs */
#include "Bsp.h"                    /* Include waitTime APIs */

/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/

/* Define buzzer port */
#define BUZZER_PORT                 &MODULE_P33

/* Define buzzer pin: P33.0 */
#define BUZZER_PIN                  0

/* Define buzzer half period in microseconds */
#define BUZZER_HALF_PERIOD_US       244
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
    /* Debug: 1 when buzzer is active */
    volatile uint32 g_debugBuzzerActive = 0;

/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/

    /* Initialize buzzer pin */
    void Buzzer_Init(void)
    {
        /* Configure P33.0 as output push-pull */
        IfxPort_setPinModeOutput(BUZZER_PORT, BUZZER_PIN, IfxPort_OutputMode_pushPull, IfxPort_OutputIdx_general);

        /* Start with buzzer off */
        IfxPort_setPinLow(BUZZER_PORT, BUZZER_PIN);

        /* Save buzzer state */
        g_debugBuzzerActive = 0;
    }

    /* Turn buzzer off */
    void Buzzer_Off(void)
    {
        /* Force buzzer pin LOW */
        IfxPort_setPinLow(BUZZER_PORT, BUZZER_PIN);

        /* Save buzzer state */
        g_debugBuzzerActive = 0;
    }

    /* Run buzzer sound */
    void Buzzer_BeepTask(void)
    {
        /* Save buzzer active state */
        g_debugBuzzerActive = 1;

        /* Toggle buzzer pin */
        IfxPort_togglePin(BUZZER_PORT, BUZZER_PIN);

        /* Wait to generate sound */
        waitTime(IfxStm_getTicksFromMicroseconds(BSP_DEFAULT_TIMER, BUZZER_HALF_PERIOD_US));
    }
/*********************************************************************************************************************/
