/**********************************************************************************************************************
 * \file Ethernet_Handler.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/




/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
#include "Ethernet_Handler.h"       /* Include ethernet handler public API */
#include "Fault_Manager.h"          /* Include fault manager API */
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/

/* Debug: write command from Expressions to simulate ethernet frame */
volatile uint32 g_debugEthCommandInject = ETH_CMD_NONE;

/* Debug: last handled ethernet command */
volatile uint32 g_debugLastEthCommand = ETH_CMD_NONE;
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
    /* Initialize ethernet handler */
    void EthernetHandler_Init(void)
    {
        /* Clear debug injected command */
        g_debugEthCommandInject = ETH_CMD_NONE;

        /* Clear last handled command */
        g_debugLastEthCommand = ETH_CMD_NONE;
    }

    /* Handle one received ethernet frame */
    void EthernetHandler_HandleFrame(const EthernetFrame_t *frame)
    {
        /* Check if frame pointer is valid */
        if (frame == 0)
        {
            /* Return if frame pointer is invalid */
            return;
        }

        /* Store last handled command for debug */
        g_debugLastEthCommand = frame->command;

        /* Handle command */
        switch (frame->command)
        {
            case ETH_CMD_INJECT_FAULT:
            {
                /* Set ethernet fault active */
                FaultManager_SetEthernetFault(TRUE);

                /* Stop this case */
                break;
            }

            case ETH_CMD_CLEAR_FAULT:
            {
                /* Clear ethernet fault */
                FaultManager_SetEthernetFault(FALSE);

                /* Stop this case */
                break;
            }

            case ETH_CMD_GET_STATUS:
            {
                /* Status response will be added later */
                break;
            }

            default:
            {
                /* Ignore unknown command */
                break;
            }
        }
    }

    /* Simulate ethernet command from debugger */
    void EthernetHandler_DebugCommandTask(void)
    {
        /* Create local fake frame */
        EthernetFrame_t frame;

        /* Check if there is no debug command */
        if (g_debugEthCommandInject == ETH_CMD_NONE)
        {
            /* Return if no command exists */
            return;
        }

        /* Copy debug command to fake frame */
        frame.command = g_debugEthCommandInject;

        /* Clear optional value */
        frame.value = 0;

        /* Clear debug command before handling to avoid repeated execution */
        g_debugEthCommandInject = ETH_CMD_NONE;

        /* Handle fake ethernet frame */
        EthernetHandler_HandleFrame(&frame);
    }
/*********************************************************************************************************************/
