/**********************************************************************************************************************
 * \file Fault_Manager.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/




/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
#include "Fault_Manager.h"          /* Include fault manager public API */

/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/

    /* Store button fault source */
    static boolean g_buttonFault = FALSE;

    /* Store ethernet fault source */
    static boolean g_ethernetFault = FALSE;

    /* Store final fault state */
    static boolean g_faultActive = FALSE;

    /* Debug: button fault source */
    volatile uint32 g_debugButtonFault = 0;

    /* Debug: ethernet fault source */
    volatile uint32 g_debugEthernetFault = 0;

    /* Debug: final fault state */
    volatile uint32 g_debugFaultActive = 0;
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/

    /* Initialize fault manager */
    void FaultManager_Init(void)
    {
        /* Clear button fault */
        g_buttonFault = FALSE;

        /* Clear ethernet fault */
        g_ethernetFault = FALSE;

        /* Clear final fault */
        g_faultActive = FALSE;

        /* Clear debug button fault */
        g_debugButtonFault = 0;

        /* Clear debug ethernet fault */
        g_debugEthernetFault = 0;

        /* Clear debug final fault */
        g_debugFaultActive = 0;
    }

    /* Set button fault source */
    void FaultManager_SetButtonFault(boolean active)
    {
        /* Store button fault state */
        g_buttonFault = active;

        /* Store button fault state for debug */
        g_debugButtonFault = (uint32)active;
    }

    /* Set ethernet fault source */
    void FaultManager_SetEthernetFault(boolean active)
    {
        /* Store ethernet fault state */
        g_ethernetFault = active;

        /* Store ethernet fault state for debug */
        g_debugEthernetFault = (uint32)active;
    }

    /* Update final fault state */
    void FaultManager_Update(void)
    {
        /* Final fault is active if any fault source is active */
        g_faultActive = g_buttonFault || g_ethernetFault;

        /* Store final fault state for debug */
        g_debugFaultActive = (uint32)g_faultActive;
    }

    /* Return final fault state */
    boolean FaultManager_IsFaultActive(void)
    {
        /* Return final fault state */
        return g_faultActive;
    }
/*********************************************************************************************************************/
