/**********************************************************************************************************************
 * \file Ethernet_Handler.h
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

#ifndef APPLICATION_INC_ETHERNET_HANDLER_H_
#define APPLICATION_INC_ETHERNET_HANDLER_H_

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
#include "Ifx_Types.h"              /* Include Infineon basic types */

/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/

 /* Define ethernet command: no command */
#define ETH_CMD_NONE                0u

/* Define ethernet command: inject fault */
#define ETH_CMD_INJECT_FAULT        1u

/* Define ethernet command: clear fault */
#define ETH_CMD_CLEAR_FAULT         2u

/* Define ethernet command: get status */
#define ETH_CMD_GET_STATUS          3u
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/* Debug: write 1 or 2 from Expressions to simulate ethernet command */
extern volatile uint32 g_debugEthCommandInject;

/* Debug: last handled ethernet command */
extern volatile uint32 g_debugLastEthCommand;
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Data Structures---------------------------------------------------*/
/* Fake ethernet frame structure */
typedef struct
{
    uint32 command;                  /* Command ID */
    uint32 value;                    /* Optional command value */
} EthernetFrame_t;
/*********************************************************************************************************************/
 
/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
    /* Initialize ethernet handler */
    void EthernetHandler_Init(void);

    /* Handle one received ethernet frame */
    void EthernetHandler_HandleFrame(const EthernetFrame_t *frame);

    /* Simulate ethernet command from debugger */
    void EthernetHandler_DebugCommandTask(void);
/*********************************************************************************************************************/


#endif /* APPLICATION_INC_ETHERNET_HANDLER_H_ */
